source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'EasyRest_Example' do
  pod 'EasyRest', :path => '../'
  pod 'EasyRest/PromiseKit', :path => '../'
end

target 'EasyRest_Tests' do
  pod 'EasyRest', :path => '../'
  pod 'EasyRest/PromiseKit', :path => '../'
  pod 'SwiftyJSON'
  pod 'ZIPFoundation'
end

