source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'EasyRest_Example', :exclusive => true do
  pod 'EasyRest', :path => '../'
end

target 'EasyRest_Tests', :exclusive => true do
  pod 'EasyRest', :path => '../'
end
