source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'EasyRest_Example' do
  pod 'EasyRest', :path => '../'
  pod 'EasyRest/LoggerBeaver', :path => '../'
end

target 'EasyRest_Tests' do
  pod 'EasyRest', :path => '../'
end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        compatibility_pods = ['Genome']
        if compatibility_pods.include? target.name
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3.2'
            end
        end
    end
end
